// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package dodopayments

import (
	"context"
	"net/http"

	"github.com/stainless-sdks/dodo-payments-go/internal/requestconfig"
	"github.com/stainless-sdks/dodo-payments-go/option"
)

// CheckoutSupportedCountryService contains methods and other services that help
// with interacting with the dodopayments API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCheckoutSupportedCountryService] method instead.
type CheckoutSupportedCountryService struct {
	Options []option.RequestOption
}

// NewCheckoutSupportedCountryService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewCheckoutSupportedCountryService(opts ...option.RequestOption) (r *CheckoutSupportedCountryService) {
	r = &CheckoutSupportedCountryService{}
	r.Options = opts
	return
}

func (r *CheckoutSupportedCountryService) List(ctx context.Context, opts ...option.RequestOption) (res *[]CountryCodeAlpha2, err error) {
	opts = append(r.Options[:], opts...)
	path := "checkout/supported_countries"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

// ISO country code alpha2 variant
type CountryCodeAlpha2 string

const (
	CountryCodeAlpha2Af CountryCodeAlpha2 = "AF"
	CountryCodeAlpha2Ax CountryCodeAlpha2 = "AX"
	CountryCodeAlpha2Al CountryCodeAlpha2 = "AL"
	CountryCodeAlpha2Dz CountryCodeAlpha2 = "DZ"
	CountryCodeAlpha2As CountryCodeAlpha2 = "AS"
	CountryCodeAlpha2Ad CountryCodeAlpha2 = "AD"
	CountryCodeAlpha2Ao CountryCodeAlpha2 = "AO"
	CountryCodeAlpha2AI CountryCodeAlpha2 = "AI"
	CountryCodeAlpha2Aq CountryCodeAlpha2 = "AQ"
	CountryCodeAlpha2Ag CountryCodeAlpha2 = "AG"
	CountryCodeAlpha2Ar CountryCodeAlpha2 = "AR"
	CountryCodeAlpha2Am CountryCodeAlpha2 = "AM"
	CountryCodeAlpha2Aw CountryCodeAlpha2 = "AW"
	CountryCodeAlpha2Au CountryCodeAlpha2 = "AU"
	CountryCodeAlpha2At CountryCodeAlpha2 = "AT"
	CountryCodeAlpha2Az CountryCodeAlpha2 = "AZ"
	CountryCodeAlpha2Bs CountryCodeAlpha2 = "BS"
	CountryCodeAlpha2Bh CountryCodeAlpha2 = "BH"
	CountryCodeAlpha2Bd CountryCodeAlpha2 = "BD"
	CountryCodeAlpha2Bb CountryCodeAlpha2 = "BB"
	CountryCodeAlpha2By CountryCodeAlpha2 = "BY"
	CountryCodeAlpha2Be CountryCodeAlpha2 = "BE"
	CountryCodeAlpha2Bz CountryCodeAlpha2 = "BZ"
	CountryCodeAlpha2Bj CountryCodeAlpha2 = "BJ"
	CountryCodeAlpha2Bm CountryCodeAlpha2 = "BM"
	CountryCodeAlpha2Bt CountryCodeAlpha2 = "BT"
	CountryCodeAlpha2Bo CountryCodeAlpha2 = "BO"
	CountryCodeAlpha2Bq CountryCodeAlpha2 = "BQ"
	CountryCodeAlpha2Ba CountryCodeAlpha2 = "BA"
	CountryCodeAlpha2Bw CountryCodeAlpha2 = "BW"
	CountryCodeAlpha2Bv CountryCodeAlpha2 = "BV"
	CountryCodeAlpha2Br CountryCodeAlpha2 = "BR"
	CountryCodeAlpha2Io CountryCodeAlpha2 = "IO"
	CountryCodeAlpha2Bn CountryCodeAlpha2 = "BN"
	CountryCodeAlpha2Bg CountryCodeAlpha2 = "BG"
	CountryCodeAlpha2Bf CountryCodeAlpha2 = "BF"
	CountryCodeAlpha2Bi CountryCodeAlpha2 = "BI"
	CountryCodeAlpha2Kh CountryCodeAlpha2 = "KH"
	CountryCodeAlpha2Cm CountryCodeAlpha2 = "CM"
	CountryCodeAlpha2Ca CountryCodeAlpha2 = "CA"
	CountryCodeAlpha2Cv CountryCodeAlpha2 = "CV"
	CountryCodeAlpha2Ky CountryCodeAlpha2 = "KY"
	CountryCodeAlpha2Cf CountryCodeAlpha2 = "CF"
	CountryCodeAlpha2Td CountryCodeAlpha2 = "TD"
	CountryCodeAlpha2Cl CountryCodeAlpha2 = "CL"
	CountryCodeAlpha2Cn CountryCodeAlpha2 = "CN"
	CountryCodeAlpha2Cx CountryCodeAlpha2 = "CX"
	CountryCodeAlpha2Cc CountryCodeAlpha2 = "CC"
	CountryCodeAlpha2Co CountryCodeAlpha2 = "CO"
	CountryCodeAlpha2Km CountryCodeAlpha2 = "KM"
	CountryCodeAlpha2Cg CountryCodeAlpha2 = "CG"
	CountryCodeAlpha2Cd CountryCodeAlpha2 = "CD"
	CountryCodeAlpha2Ck CountryCodeAlpha2 = "CK"
	CountryCodeAlpha2Cr CountryCodeAlpha2 = "CR"
	CountryCodeAlpha2Ci CountryCodeAlpha2 = "CI"
	CountryCodeAlpha2Hr CountryCodeAlpha2 = "HR"
	CountryCodeAlpha2Cu CountryCodeAlpha2 = "CU"
	CountryCodeAlpha2Cw CountryCodeAlpha2 = "CW"
	CountryCodeAlpha2Cy CountryCodeAlpha2 = "CY"
	CountryCodeAlpha2Cz CountryCodeAlpha2 = "CZ"
	CountryCodeAlpha2Dk CountryCodeAlpha2 = "DK"
	CountryCodeAlpha2Dj CountryCodeAlpha2 = "DJ"
	CountryCodeAlpha2Dm CountryCodeAlpha2 = "DM"
	CountryCodeAlpha2Do CountryCodeAlpha2 = "DO"
	CountryCodeAlpha2Ec CountryCodeAlpha2 = "EC"
	CountryCodeAlpha2Eg CountryCodeAlpha2 = "EG"
	CountryCodeAlpha2Sv CountryCodeAlpha2 = "SV"
	CountryCodeAlpha2Gq CountryCodeAlpha2 = "GQ"
	CountryCodeAlpha2Er CountryCodeAlpha2 = "ER"
	CountryCodeAlpha2Ee CountryCodeAlpha2 = "EE"
	CountryCodeAlpha2Et CountryCodeAlpha2 = "ET"
	CountryCodeAlpha2Fk CountryCodeAlpha2 = "FK"
	CountryCodeAlpha2Fo CountryCodeAlpha2 = "FO"
	CountryCodeAlpha2Fj CountryCodeAlpha2 = "FJ"
	CountryCodeAlpha2Fi CountryCodeAlpha2 = "FI"
	CountryCodeAlpha2Fr CountryCodeAlpha2 = "FR"
	CountryCodeAlpha2Gf CountryCodeAlpha2 = "GF"
	CountryCodeAlpha2Pf CountryCodeAlpha2 = "PF"
	CountryCodeAlpha2Tf CountryCodeAlpha2 = "TF"
	CountryCodeAlpha2Ga CountryCodeAlpha2 = "GA"
	CountryCodeAlpha2Gm CountryCodeAlpha2 = "GM"
	CountryCodeAlpha2Ge CountryCodeAlpha2 = "GE"
	CountryCodeAlpha2De CountryCodeAlpha2 = "DE"
	CountryCodeAlpha2Gh CountryCodeAlpha2 = "GH"
	CountryCodeAlpha2Gi CountryCodeAlpha2 = "GI"
	CountryCodeAlpha2Gr CountryCodeAlpha2 = "GR"
	CountryCodeAlpha2Gl CountryCodeAlpha2 = "GL"
	CountryCodeAlpha2Gd CountryCodeAlpha2 = "GD"
	CountryCodeAlpha2Gp CountryCodeAlpha2 = "GP"
	CountryCodeAlpha2Gu CountryCodeAlpha2 = "GU"
	CountryCodeAlpha2Gt CountryCodeAlpha2 = "GT"
	CountryCodeAlpha2Gg CountryCodeAlpha2 = "GG"
	CountryCodeAlpha2Gn CountryCodeAlpha2 = "GN"
	CountryCodeAlpha2Gw CountryCodeAlpha2 = "GW"
	CountryCodeAlpha2Gy CountryCodeAlpha2 = "GY"
	CountryCodeAlpha2Ht CountryCodeAlpha2 = "HT"
	CountryCodeAlpha2Hm CountryCodeAlpha2 = "HM"
	CountryCodeAlpha2Va CountryCodeAlpha2 = "VA"
	CountryCodeAlpha2Hn CountryCodeAlpha2 = "HN"
	CountryCodeAlpha2Hk CountryCodeAlpha2 = "HK"
	CountryCodeAlpha2Hu CountryCodeAlpha2 = "HU"
	CountryCodeAlpha2Is CountryCodeAlpha2 = "IS"
	CountryCodeAlpha2In CountryCodeAlpha2 = "IN"
	CountryCodeAlpha2ID CountryCodeAlpha2 = "ID"
	CountryCodeAlpha2Ir CountryCodeAlpha2 = "IR"
	CountryCodeAlpha2Iq CountryCodeAlpha2 = "IQ"
	CountryCodeAlpha2Ie CountryCodeAlpha2 = "IE"
	CountryCodeAlpha2Im CountryCodeAlpha2 = "IM"
	CountryCodeAlpha2Il CountryCodeAlpha2 = "IL"
	CountryCodeAlpha2It CountryCodeAlpha2 = "IT"
	CountryCodeAlpha2Jm CountryCodeAlpha2 = "JM"
	CountryCodeAlpha2Jp CountryCodeAlpha2 = "JP"
	CountryCodeAlpha2Je CountryCodeAlpha2 = "JE"
	CountryCodeAlpha2Jo CountryCodeAlpha2 = "JO"
	CountryCodeAlpha2Kz CountryCodeAlpha2 = "KZ"
	CountryCodeAlpha2Ke CountryCodeAlpha2 = "KE"
	CountryCodeAlpha2Ki CountryCodeAlpha2 = "KI"
	CountryCodeAlpha2Kp CountryCodeAlpha2 = "KP"
	CountryCodeAlpha2Kr CountryCodeAlpha2 = "KR"
	CountryCodeAlpha2Kw CountryCodeAlpha2 = "KW"
	CountryCodeAlpha2Kg CountryCodeAlpha2 = "KG"
	CountryCodeAlpha2La CountryCodeAlpha2 = "LA"
	CountryCodeAlpha2Lv CountryCodeAlpha2 = "LV"
	CountryCodeAlpha2Lb CountryCodeAlpha2 = "LB"
	CountryCodeAlpha2Ls CountryCodeAlpha2 = "LS"
	CountryCodeAlpha2Lr CountryCodeAlpha2 = "LR"
	CountryCodeAlpha2Ly CountryCodeAlpha2 = "LY"
	CountryCodeAlpha2Li CountryCodeAlpha2 = "LI"
	CountryCodeAlpha2Lt CountryCodeAlpha2 = "LT"
	CountryCodeAlpha2Lu CountryCodeAlpha2 = "LU"
	CountryCodeAlpha2Mo CountryCodeAlpha2 = "MO"
	CountryCodeAlpha2Mk CountryCodeAlpha2 = "MK"
	CountryCodeAlpha2Mg CountryCodeAlpha2 = "MG"
	CountryCodeAlpha2Mw CountryCodeAlpha2 = "MW"
	CountryCodeAlpha2My CountryCodeAlpha2 = "MY"
	CountryCodeAlpha2Mv CountryCodeAlpha2 = "MV"
	CountryCodeAlpha2Ml CountryCodeAlpha2 = "ML"
	CountryCodeAlpha2Mt CountryCodeAlpha2 = "MT"
	CountryCodeAlpha2Mh CountryCodeAlpha2 = "MH"
	CountryCodeAlpha2Mq CountryCodeAlpha2 = "MQ"
	CountryCodeAlpha2Mr CountryCodeAlpha2 = "MR"
	CountryCodeAlpha2Mu CountryCodeAlpha2 = "MU"
	CountryCodeAlpha2Yt CountryCodeAlpha2 = "YT"
	CountryCodeAlpha2Mx CountryCodeAlpha2 = "MX"
	CountryCodeAlpha2Fm CountryCodeAlpha2 = "FM"
	CountryCodeAlpha2Md CountryCodeAlpha2 = "MD"
	CountryCodeAlpha2Mc CountryCodeAlpha2 = "MC"
	CountryCodeAlpha2Mn CountryCodeAlpha2 = "MN"
	CountryCodeAlpha2Me CountryCodeAlpha2 = "ME"
	CountryCodeAlpha2Ms CountryCodeAlpha2 = "MS"
	CountryCodeAlpha2Ma CountryCodeAlpha2 = "MA"
	CountryCodeAlpha2Mz CountryCodeAlpha2 = "MZ"
	CountryCodeAlpha2Mm CountryCodeAlpha2 = "MM"
	CountryCodeAlpha2Na CountryCodeAlpha2 = "NA"
	CountryCodeAlpha2Nr CountryCodeAlpha2 = "NR"
	CountryCodeAlpha2Np CountryCodeAlpha2 = "NP"
	CountryCodeAlpha2Nl CountryCodeAlpha2 = "NL"
	CountryCodeAlpha2Nc CountryCodeAlpha2 = "NC"
	CountryCodeAlpha2Nz CountryCodeAlpha2 = "NZ"
	CountryCodeAlpha2Ni CountryCodeAlpha2 = "NI"
	CountryCodeAlpha2Ne CountryCodeAlpha2 = "NE"
	CountryCodeAlpha2Ng CountryCodeAlpha2 = "NG"
	CountryCodeAlpha2Nu CountryCodeAlpha2 = "NU"
	CountryCodeAlpha2Nf CountryCodeAlpha2 = "NF"
	CountryCodeAlpha2Mp CountryCodeAlpha2 = "MP"
	CountryCodeAlpha2No CountryCodeAlpha2 = "NO"
	CountryCodeAlpha2Om CountryCodeAlpha2 = "OM"
	CountryCodeAlpha2Pk CountryCodeAlpha2 = "PK"
	CountryCodeAlpha2Pw CountryCodeAlpha2 = "PW"
	CountryCodeAlpha2Ps CountryCodeAlpha2 = "PS"
	CountryCodeAlpha2Pa CountryCodeAlpha2 = "PA"
	CountryCodeAlpha2Pg CountryCodeAlpha2 = "PG"
	CountryCodeAlpha2Py CountryCodeAlpha2 = "PY"
	CountryCodeAlpha2Pe CountryCodeAlpha2 = "PE"
	CountryCodeAlpha2Ph CountryCodeAlpha2 = "PH"
	CountryCodeAlpha2Pn CountryCodeAlpha2 = "PN"
	CountryCodeAlpha2Pl CountryCodeAlpha2 = "PL"
	CountryCodeAlpha2Pt CountryCodeAlpha2 = "PT"
	CountryCodeAlpha2Pr CountryCodeAlpha2 = "PR"
	CountryCodeAlpha2Qa CountryCodeAlpha2 = "QA"
	CountryCodeAlpha2Re CountryCodeAlpha2 = "RE"
	CountryCodeAlpha2Ro CountryCodeAlpha2 = "RO"
	CountryCodeAlpha2Ru CountryCodeAlpha2 = "RU"
	CountryCodeAlpha2Rw CountryCodeAlpha2 = "RW"
	CountryCodeAlpha2Bl CountryCodeAlpha2 = "BL"
	CountryCodeAlpha2Sh CountryCodeAlpha2 = "SH"
	CountryCodeAlpha2Kn CountryCodeAlpha2 = "KN"
	CountryCodeAlpha2Lc CountryCodeAlpha2 = "LC"
	CountryCodeAlpha2Mf CountryCodeAlpha2 = "MF"
	CountryCodeAlpha2Pm CountryCodeAlpha2 = "PM"
	CountryCodeAlpha2Vc CountryCodeAlpha2 = "VC"
	CountryCodeAlpha2Ws CountryCodeAlpha2 = "WS"
	CountryCodeAlpha2Sm CountryCodeAlpha2 = "SM"
	CountryCodeAlpha2St CountryCodeAlpha2 = "ST"
	CountryCodeAlpha2Sa CountryCodeAlpha2 = "SA"
	CountryCodeAlpha2Sn CountryCodeAlpha2 = "SN"
	CountryCodeAlpha2Rs CountryCodeAlpha2 = "RS"
	CountryCodeAlpha2Sc CountryCodeAlpha2 = "SC"
	CountryCodeAlpha2Sl CountryCodeAlpha2 = "SL"
	CountryCodeAlpha2Sg CountryCodeAlpha2 = "SG"
	CountryCodeAlpha2Sx CountryCodeAlpha2 = "SX"
	CountryCodeAlpha2Sk CountryCodeAlpha2 = "SK"
	CountryCodeAlpha2Si CountryCodeAlpha2 = "SI"
	CountryCodeAlpha2Sb CountryCodeAlpha2 = "SB"
	CountryCodeAlpha2So CountryCodeAlpha2 = "SO"
	CountryCodeAlpha2Za CountryCodeAlpha2 = "ZA"
	CountryCodeAlpha2Gs CountryCodeAlpha2 = "GS"
	CountryCodeAlpha2SS CountryCodeAlpha2 = "SS"
	CountryCodeAlpha2Es CountryCodeAlpha2 = "ES"
	CountryCodeAlpha2Lk CountryCodeAlpha2 = "LK"
	CountryCodeAlpha2Sd CountryCodeAlpha2 = "SD"
	CountryCodeAlpha2Sr CountryCodeAlpha2 = "SR"
	CountryCodeAlpha2Sj CountryCodeAlpha2 = "SJ"
	CountryCodeAlpha2Sz CountryCodeAlpha2 = "SZ"
	CountryCodeAlpha2Se CountryCodeAlpha2 = "SE"
	CountryCodeAlpha2Ch CountryCodeAlpha2 = "CH"
	CountryCodeAlpha2Sy CountryCodeAlpha2 = "SY"
	CountryCodeAlpha2Tw CountryCodeAlpha2 = "TW"
	CountryCodeAlpha2Tj CountryCodeAlpha2 = "TJ"
	CountryCodeAlpha2Tz CountryCodeAlpha2 = "TZ"
	CountryCodeAlpha2Th CountryCodeAlpha2 = "TH"
	CountryCodeAlpha2Tl CountryCodeAlpha2 = "TL"
	CountryCodeAlpha2Tg CountryCodeAlpha2 = "TG"
	CountryCodeAlpha2Tk CountryCodeAlpha2 = "TK"
	CountryCodeAlpha2To CountryCodeAlpha2 = "TO"
	CountryCodeAlpha2Tt CountryCodeAlpha2 = "TT"
	CountryCodeAlpha2Tn CountryCodeAlpha2 = "TN"
	CountryCodeAlpha2Tr CountryCodeAlpha2 = "TR"
	CountryCodeAlpha2Tm CountryCodeAlpha2 = "TM"
	CountryCodeAlpha2Tc CountryCodeAlpha2 = "TC"
	CountryCodeAlpha2Tv CountryCodeAlpha2 = "TV"
	CountryCodeAlpha2Ug CountryCodeAlpha2 = "UG"
	CountryCodeAlpha2Ua CountryCodeAlpha2 = "UA"
	CountryCodeAlpha2Ae CountryCodeAlpha2 = "AE"
	CountryCodeAlpha2GB CountryCodeAlpha2 = "GB"
	CountryCodeAlpha2Um CountryCodeAlpha2 = "UM"
	CountryCodeAlpha2Us CountryCodeAlpha2 = "US"
	CountryCodeAlpha2Uy CountryCodeAlpha2 = "UY"
	CountryCodeAlpha2Uz CountryCodeAlpha2 = "UZ"
	CountryCodeAlpha2Vu CountryCodeAlpha2 = "VU"
	CountryCodeAlpha2Ve CountryCodeAlpha2 = "VE"
	CountryCodeAlpha2Vn CountryCodeAlpha2 = "VN"
	CountryCodeAlpha2Vg CountryCodeAlpha2 = "VG"
	CountryCodeAlpha2Vi CountryCodeAlpha2 = "VI"
	CountryCodeAlpha2Wf CountryCodeAlpha2 = "WF"
	CountryCodeAlpha2Eh CountryCodeAlpha2 = "EH"
	CountryCodeAlpha2Ye CountryCodeAlpha2 = "YE"
	CountryCodeAlpha2Zm CountryCodeAlpha2 = "ZM"
	CountryCodeAlpha2Zw CountryCodeAlpha2 = "ZW"
)

func (r CountryCodeAlpha2) IsKnown() bool {
	switch r {
	case CountryCodeAlpha2Af, CountryCodeAlpha2Ax, CountryCodeAlpha2Al, CountryCodeAlpha2Dz, CountryCodeAlpha2As, CountryCodeAlpha2Ad, CountryCodeAlpha2Ao, CountryCodeAlpha2AI, CountryCodeAlpha2Aq, CountryCodeAlpha2Ag, CountryCodeAlpha2Ar, CountryCodeAlpha2Am, CountryCodeAlpha2Aw, CountryCodeAlpha2Au, CountryCodeAlpha2At, CountryCodeAlpha2Az, CountryCodeAlpha2Bs, CountryCodeAlpha2Bh, CountryCodeAlpha2Bd, CountryCodeAlpha2Bb, CountryCodeAlpha2By, CountryCodeAlpha2Be, CountryCodeAlpha2Bz, CountryCodeAlpha2Bj, CountryCodeAlpha2Bm, CountryCodeAlpha2Bt, CountryCodeAlpha2Bo, CountryCodeAlpha2Bq, CountryCodeAlpha2Ba, CountryCodeAlpha2Bw, CountryCodeAlpha2Bv, CountryCodeAlpha2Br, CountryCodeAlpha2Io, CountryCodeAlpha2Bn, CountryCodeAlpha2Bg, CountryCodeAlpha2Bf, CountryCodeAlpha2Bi, CountryCodeAlpha2Kh, CountryCodeAlpha2Cm, CountryCodeAlpha2Ca, CountryCodeAlpha2Cv, CountryCodeAlpha2Ky, CountryCodeAlpha2Cf, CountryCodeAlpha2Td, CountryCodeAlpha2Cl, CountryCodeAlpha2Cn, CountryCodeAlpha2Cx, CountryCodeAlpha2Cc, CountryCodeAlpha2Co, CountryCodeAlpha2Km, CountryCodeAlpha2Cg, CountryCodeAlpha2Cd, CountryCodeAlpha2Ck, CountryCodeAlpha2Cr, CountryCodeAlpha2Ci, CountryCodeAlpha2Hr, CountryCodeAlpha2Cu, CountryCodeAlpha2Cw, CountryCodeAlpha2Cy, CountryCodeAlpha2Cz, CountryCodeAlpha2Dk, CountryCodeAlpha2Dj, CountryCodeAlpha2Dm, CountryCodeAlpha2Do, CountryCodeAlpha2Ec, CountryCodeAlpha2Eg, CountryCodeAlpha2Sv, CountryCodeAlpha2Gq, CountryCodeAlpha2Er, CountryCodeAlpha2Ee, CountryCodeAlpha2Et, CountryCodeAlpha2Fk, CountryCodeAlpha2Fo, CountryCodeAlpha2Fj, CountryCodeAlpha2Fi, CountryCodeAlpha2Fr, CountryCodeAlpha2Gf, CountryCodeAlpha2Pf, CountryCodeAlpha2Tf, CountryCodeAlpha2Ga, CountryCodeAlpha2Gm, CountryCodeAlpha2Ge, CountryCodeAlpha2De, CountryCodeAlpha2Gh, CountryCodeAlpha2Gi, CountryCodeAlpha2Gr, CountryCodeAlpha2Gl, CountryCodeAlpha2Gd, CountryCodeAlpha2Gp, CountryCodeAlpha2Gu, CountryCodeAlpha2Gt, CountryCodeAlpha2Gg, CountryCodeAlpha2Gn, CountryCodeAlpha2Gw, CountryCodeAlpha2Gy, CountryCodeAlpha2Ht, CountryCodeAlpha2Hm, CountryCodeAlpha2Va, CountryCodeAlpha2Hn, CountryCodeAlpha2Hk, CountryCodeAlpha2Hu, CountryCodeAlpha2Is, CountryCodeAlpha2In, CountryCodeAlpha2ID, CountryCodeAlpha2Ir, CountryCodeAlpha2Iq, CountryCodeAlpha2Ie, CountryCodeAlpha2Im, CountryCodeAlpha2Il, CountryCodeAlpha2It, CountryCodeAlpha2Jm, CountryCodeAlpha2Jp, CountryCodeAlpha2Je, CountryCodeAlpha2Jo, CountryCodeAlpha2Kz, CountryCodeAlpha2Ke, CountryCodeAlpha2Ki, CountryCodeAlpha2Kp, CountryCodeAlpha2Kr, CountryCodeAlpha2Kw, CountryCodeAlpha2Kg, CountryCodeAlpha2La, CountryCodeAlpha2Lv, CountryCodeAlpha2Lb, CountryCodeAlpha2Ls, CountryCodeAlpha2Lr, CountryCodeAlpha2Ly, CountryCodeAlpha2Li, CountryCodeAlpha2Lt, CountryCodeAlpha2Lu, CountryCodeAlpha2Mo, CountryCodeAlpha2Mk, CountryCodeAlpha2Mg, CountryCodeAlpha2Mw, CountryCodeAlpha2My, CountryCodeAlpha2Mv, CountryCodeAlpha2Ml, CountryCodeAlpha2Mt, CountryCodeAlpha2Mh, CountryCodeAlpha2Mq, CountryCodeAlpha2Mr, CountryCodeAlpha2Mu, CountryCodeAlpha2Yt, CountryCodeAlpha2Mx, CountryCodeAlpha2Fm, CountryCodeAlpha2Md, CountryCodeAlpha2Mc, CountryCodeAlpha2Mn, CountryCodeAlpha2Me, CountryCodeAlpha2Ms, CountryCodeAlpha2Ma, CountryCodeAlpha2Mz, CountryCodeAlpha2Mm, CountryCodeAlpha2Na, CountryCodeAlpha2Nr, CountryCodeAlpha2Np, CountryCodeAlpha2Nl, CountryCodeAlpha2Nc, CountryCodeAlpha2Nz, CountryCodeAlpha2Ni, CountryCodeAlpha2Ne, CountryCodeAlpha2Ng, CountryCodeAlpha2Nu, CountryCodeAlpha2Nf, CountryCodeAlpha2Mp, CountryCodeAlpha2No, CountryCodeAlpha2Om, CountryCodeAlpha2Pk, CountryCodeAlpha2Pw, CountryCodeAlpha2Ps, CountryCodeAlpha2Pa, CountryCodeAlpha2Pg, CountryCodeAlpha2Py, CountryCodeAlpha2Pe, CountryCodeAlpha2Ph, CountryCodeAlpha2Pn, CountryCodeAlpha2Pl, CountryCodeAlpha2Pt, CountryCodeAlpha2Pr, CountryCodeAlpha2Qa, CountryCodeAlpha2Re, CountryCodeAlpha2Ro, CountryCodeAlpha2Ru, CountryCodeAlpha2Rw, CountryCodeAlpha2Bl, CountryCodeAlpha2Sh, CountryCodeAlpha2Kn, CountryCodeAlpha2Lc, CountryCodeAlpha2Mf, CountryCodeAlpha2Pm, CountryCodeAlpha2Vc, CountryCodeAlpha2Ws, CountryCodeAlpha2Sm, CountryCodeAlpha2St, CountryCodeAlpha2Sa, CountryCodeAlpha2Sn, CountryCodeAlpha2Rs, CountryCodeAlpha2Sc, CountryCodeAlpha2Sl, CountryCodeAlpha2Sg, CountryCodeAlpha2Sx, CountryCodeAlpha2Sk, CountryCodeAlpha2Si, CountryCodeAlpha2Sb, CountryCodeAlpha2So, CountryCodeAlpha2Za, CountryCodeAlpha2Gs, CountryCodeAlpha2SS, CountryCodeAlpha2Es, CountryCodeAlpha2Lk, CountryCodeAlpha2Sd, CountryCodeAlpha2Sr, CountryCodeAlpha2Sj, CountryCodeAlpha2Sz, CountryCodeAlpha2Se, CountryCodeAlpha2Ch, CountryCodeAlpha2Sy, CountryCodeAlpha2Tw, CountryCodeAlpha2Tj, CountryCodeAlpha2Tz, CountryCodeAlpha2Th, CountryCodeAlpha2Tl, CountryCodeAlpha2Tg, CountryCodeAlpha2Tk, CountryCodeAlpha2To, CountryCodeAlpha2Tt, CountryCodeAlpha2Tn, CountryCodeAlpha2Tr, CountryCodeAlpha2Tm, CountryCodeAlpha2Tc, CountryCodeAlpha2Tv, CountryCodeAlpha2Ug, CountryCodeAlpha2Ua, CountryCodeAlpha2Ae, CountryCodeAlpha2GB, CountryCodeAlpha2Um, CountryCodeAlpha2Us, CountryCodeAlpha2Uy, CountryCodeAlpha2Uz, CountryCodeAlpha2Vu, CountryCodeAlpha2Ve, CountryCodeAlpha2Vn, CountryCodeAlpha2Vg, CountryCodeAlpha2Vi, CountryCodeAlpha2Wf, CountryCodeAlpha2Eh, CountryCodeAlpha2Ye, CountryCodeAlpha2Zm, CountryCodeAlpha2Zw:
		return true
	}
	return false
}
